* CSNAnalysis: Tools for creating, analyzing and visualizing Conformation Space Networks.

CSNAnalysis is a set of tools for network-based analysis of molecular dynamics trajectories.
To use, initialize a `CSN` object using a matrix of transition counts.
The "killer app" of CSNAnalysis is an easy interface between enhanced sampling algorithms 
(e.g. WExplore), molecular clustering programs (e.g. MSMBuilder), graph analysis packages (e.g. networkX) 
and graph visualization programs (e.g. Gephi).

CSNAnalysis is currently in beta.

* Installation
To install CSNAnalysis, clone one of the releases and manually install it.

#+BEGIN_SRC bash
  git clone https://gitlab.com/ADicksonLab/CSNAnalysis
  cd CSNAnalysis

  # install
  pip install --user -e .
#+END_SRC

* Dependencies
- numpy
- scipy
- networkx

* Features
CSNAnalysis has the following capabilities:

- constructing transition probability matrices
- trimming CSNs using a variety of criteria
- computing committor probabilities with an arbitrary number of basins
- export gexf files with custom node colorings

* Tutorial
See the Jupyter Notebook in examples/examples.ipynb

* Misc
** Versioning

See [[http://semver.org/]] for version number meanings.

Version 1.0.0 will be released whenever the abstract layer API is stable. Subsequent 1.X.y releases will be made as applied and porcelain layer features are added.
